### ISSUE TITLE
issue while getting listing

### ISSUE THREAD

**Issue by gabhi** [nodebnb/BackEnd#1]
`
Elasticsearch TRACE: 2015-06-04T05:43:24Z
  -> POST http://localhost:9200/listings/_search

  <- 404
  {
    "error": "IndexMissingException[[listings] missing]",
    "status": 404
  }

Elasticsearch DEBUG: 2015-06-04T05:43:24Z
  Request complete

Unhandled rejection Error: IndexMissingException[[listings] missing]
    at respond (/Users/agaikw1/BackEnd/node_modules/elasticsearch/src/lib/transport.js:232:15)
    at checkRespForFailure (/Users/agaikw1/BackEnd/node_modules/elasticsearch/src/lib/transport.js:200:7)
    at HttpConnector.<anonymous> (/Users/agaikw1/BackEnd/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
    at IncomingMessage.wrapper (/Users/agaikw1/BackEnd/node_modules/elasticsearch/node_modules/lodash/index.js:3128:19)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:163:7)
    at endReadableNT (_stream_readable.js:890:12)
    at doNTCallback2 (node.js:437:9)
    at process._tickDomainCallback (node.js:392:17)`

**Comment by badmonster0** [comment]
you'll need to import data and run bode indexer
